language: cpp

before_install:
  - apt update
  - apt -y install sudo lsb-release software-properties-common wget

install:
  - sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

script:
  - chmod +x ./build.sh
  - ./build.sh
