language: cpp

before_install:
  - docker pull clangbuiltlinux/debian
  - docker ps -a

install:
  - docker run clangbuiltlinux/debian /bin/sh -c "apt update"
  - docker run clangbuiltlinux/debian /bin/sh -c "apt -y install sudo lsb-release software-properties-common wget"
  - docker run clangbuiltlinux/debian /bin/sh -c "sudo bash -c '$(wget -O - https://apt.llvm.org/llvm.sh)'"

script:
  - docker run clangbuiltlinux/debian /bin/sh -c "chmod +x ./build.sh"
  - docker run clangbuiltlinux/debian /bin/sh -c "./build.sh"
